services:
  - type: web
    name: crypto-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: crypto-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: NEWSAPI_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: COINGECKO_API_KEY
        sync: false

databases:
  - name: crypto-db
    plan: free